name: todo-unofficial-cli
base: core22
version: '0.1'
summary: A CLI app for Microsoft ToDo
description: |
  An unofficial CLI app to handle your Microsoft ToDo tasks.
  Organize your life and create, delete, update your tasks from the confort 
  of the terminal or do some cool automation cron job.

grade: devel
confinement: devmode

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  todo:
    source: .
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libicu70
  appsettings:
    plugin: dump
    source: .
    stage:
      - appsettings.json

apps:
  todo-unofficial-cli:
    command: todo
    environment:
      APP_CONFIG_PATH: $SNAP/appsettings.json
    plugs:
      - network
      - network-bind
      - password-manager-service

  
